- name: Gather and print local facts
  hosts: localhost
  # become: true
  gather_facts: true
  tasks:
    - name: Print facts
      ansible.builtin.debug:
      # var: ansible_facts
        msg:
          - "{{ansible_facts.hostname}}"
          - "{{ansible_facts.user_id}}"
          - "{{ansible_facts.env.PWD}}"
